version: "3"
services:
  bot:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/api
    restart: always
    depends_on:
      - redis
  worker:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    depends_on:
      - redis
  monitor:
    build:
      context: celery-queue
      dockerfile: Dockerfile
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
